# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    command: ["/app/web.sh"]
    depends_on:
      postgres:
        condition: service_started
        restart: true
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-port:/var/run
      - static:/app/static
    stop_signal: SIGINT
    develop:
      watch:
        - action: sync
          path: ./mysite
          target: /app/mysite
        - action: sync
          path: ./cardapios
          target: /app/cardapios
        - action: sync
          path: ./static
          target: /app/static

  nginx:
    image: "nginx"
    ports:
      - 80:80
    depends_on:
      server:
        condition: service_started
        restart: true
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    volumes:
      - static:/app/static

  postgres:
    image: "postgres"
    user: postgres
    secrets:
      - db-password 
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-port:/var/run
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

volumes:
  db-data:
  db-port:
  static:

secrets:
  db-password:
    file: db/password.txt

configs:
  nginx: 
    file: config/nginx.conf
